version: "3.8"

services:
  auth:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.region == ru"  # Запускаем только на RU сервере
    image: registry.sh1bari.ru/hack/auth:1.0.0
    environment:
      - POSTGRES_ADDRESS=authpostgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - authpostgres
    networks:
      - traefik_network
      - my-custom-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authHack.rule=Host(`auth.noxly.ru`)"
      - "traefik.http.routers.authHack.entrypoints=websecure"
      - "traefik.http.routers.authHack.tls=true"
      - "traefik.http.routers.authHack.tls.certresolver=myresolver"
      - "traefik.http.services.authHack.loadbalancer.server.port=8080"
      - "traefik.http.routers.authHack.priority=21"
      - "traefik.docker.network=traefik_network"

  efs:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.region == ru"  # Запускаем только на RU сервере
    image: registry.sh1bari.ru/hack/efs:1.0.0
    networks:
      - traefik_network
      - my-custom-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.efs.rule=Host(`hack.noxly.ru`)"
      - "traefik.http.routers.efs.entrypoints=websecure"
      - "traefik.http.routers.efs.tls=true"
      - "traefik.http.routers.efs.tls.certresolver=myresolver"
      - "traefik.http.services.efs.loadbalancer.server.port=8081"
      - "traefik.http.routers.efs.priority=25"
      - "traefik.docker.network=traefik_network"

  authpostgres:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.region == ru"  # Запускаем только на RU сервере
    image: mirror.gcr.io/postgres:16.4-alpine
    networks:
      - my-custom-network
    restart: always
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data-auth:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data-auth:
    driver: local

networks:
  traefik_network:
    external: true
  my-custom-network:
    external: true
