version: "3.8"

services:

  fuelpostgres:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.region == ru"  # Запускаем только на RU сервере
    image: mirror.gcr.io/postgres:16.4-alpine
    networks:
      - my-custom-network
    restart: always
    environment:
      - POSTGRES_DB=fuel-seller
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data-fuel:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  authpostgres:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.region == ru"  # Запускаем только на RU сервере
    image: mirror.gcr.io/postgres:16.4-alpine
    networks:
      - my-custom-network
    restart: always
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data-auth:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data-auth:
    driver: local
  pg-data-fuel:
    driver: local

networks:
  traefik_network:
    external: true
  my-custom-network:
    external: true
