CREATE TABLE fuels
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fuel_type VARCHAR(255),
    CONSTRAINT pk_fuels PRIMARY KEY (id)
);

CREATE TABLE lots
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date           TIMESTAMP WITHOUT TIME ZONE,
    oil_depot_id   BIGINT,
    fuel_id        BIGINT,
    volume_of_fuel DOUBLE PRECISION,
    remaining_fuel DOUBLE PRECISION,
    CONSTRAINT pk_lots PRIMARY KEY (id)
);

CREATE TABLE oil_depots
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR,
    region VARCHAR,
    CONSTRAINT pk_oil_depots PRIMARY KEY (id)
);

ALTER TABLE lots
    ADD CONSTRAINT FK_LOTS_ON_FUEL FOREIGN KEY (fuel_id) REFERENCES fuels (id);

ALTER TABLE lots
    ADD CONSTRAINT FK_LOTS_ON_OIL_DEPOT FOREIGN KEY (oil_depot_id) REFERENCES oil_depots (id);